# EN CASO DE QUERER LEVANTAR LA APP SIN CONFIG-SERVER:
# COMENTAR COMPLETO BOOTSTRAP.YML
# - DESCOMENTAR COMPLETO APPLICATION.YML
# - CAMBIAR EL server.port EN APPLICATION.YML

#spring:
#  application:
#    name: catalog-service
#  cloud:
#    config:
#      discovery:
#        enabled: false
#
#server:
#  port: 8084
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#resilience4j:
#  circuitbreaker:
#    instances:
#      movie:
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 6
#        failureRateThreshold: 50
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 15000
#        permittedNumberOfCallsInHalfOpenState: 3
#        registerHealthIndicator: true
#        allowHealthIndicatorToFail: true
#
#management:
#  health:
#    circuitbreakers:
#      enabled: true